// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    About: typeof import("./components/About.vue")["default"];
    BaseHeader: typeof import("./components/layouts/BaseHeader.vue")["default"];
    BaseSide: typeof import("./components/layouts/BaseSide.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    Home: typeof import("./components/Home.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Settings: typeof import("./components/Settings.vue")["default"];
  }
}

export {};
